version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextjsdb
    ports:
      - 5432:5432